import { Terminal } from 'lucide-react';

// Drafted from researched industry norms for AI naming/trademark-screening tools
// (Namelix-style "not legal advice, verify independently" disclaimers; the 2026
// SaaS/AI-terms trend toward explicit AI-output-accuracy disclaimers and a
// point-of-use disclosure in addition to a dedicated terms page — a disclaimer
// buried only in a ToS page carries less legal weight than one shown where the
// user actually acts). This is a starting draft, NOT a substitute for review by
// a licensed attorney before being relied on as actual liability protection.
export function LegalPage() {
  return (
    <div className="min-h-screen bg-white text-neutral-700 font-sans">
      <nav className="sticky top-0 left-0 w-full border-b border-neutral-200 bg-white z-50">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center gap-2.5">
          <a href="/" className="flex items-center gap-2.5 hover:opacity-70 transition-opacity">
            <div className="w-7 h-7 rounded-full bg-[#7CB800] flex items-center justify-center text-white flex-shrink-0">
              <Terminal className="w-4 h-4" />
            </div>
            <span className="font-sans font-semibold text-neutral-900 tracking-tight text-base">NamingStorm</span>
          </a>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-semibold text-neutral-900 tracking-tight mb-2">Terms of Use &amp; Disclaimers</h1>
        <p className="text-sm text-neutral-400 mb-12">Last updated September 16, 2026</p>

        <div className="space-y-10 text-sm leading-relaxed text-neutral-600">
          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">1. Not Legal, Financial, or Professional Advice</h2>
            <p>
              NamingStorm is an AI-assisted naming and preliminary screening tool. Nothing it generates or
              displays — including trademark screening results, domain availability results, phonetic or
              trademark-strength scores, or brand narratives — constitutes legal advice, a legal opinion, or
              a substitute for consultation with a licensed trademark attorney. No attorney-client
              relationship is created by using this service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">2. AI-Generated Content Disclaimer</h2>
            <p>
              Names, brand rationales, phonetic profiles, and brand stories are generated by an AI model and
              may be inaccurate, incomplete, generic, similar to existing marks or brands, or otherwise
              unsuitable for your use. AI outputs are not guaranteed to be accurate, complete, novel,
              trademarkable, or free of third-party rights. You are solely responsible for independently
              reviewing and verifying any name or content before relying on it, registering a domain,
              filing a trademark application, or otherwise committing resources to it.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">3. Trademark Screening Is Preliminary Only</h2>
            <p>
              Trademark screening checks for exact and near-exact matches against live active U.S. federal
              trademark registrations (USPTO) only. It does not and cannot see: unregistered common-law
              marks, state trademark registrations, pending applications outside what the underlying data
              source indexes, foreign/international trademarks, or assess likelihood of confusion, dilution,
              or any other legal standard. A "clear" or "low risk" result is not a clearance opinion and is
              not a guarantee the name is free to use or register. Consult a trademark attorney and, where
              appropriate, order a full clearance search before filing an application or launching a brand.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">4. Domain Availability Is Time-Sensitive</h2>
            <p>
              Domain availability (.com, .io, .ai, .dev, .app, and any other TLD checked) reflects a live
              registry lookup at the moment of the check and can change at any time, including within
              seconds, due to registration by any third party. NamingStorm does not reserve, hold, broker,
              or guarantee availability of any domain and is not a domain registrar. Register any domain you
              intend to use promptly and directly through a registrar of your choice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">5. Third-Party Links</h2>
            <p>
              Links to domain registrars and aftermarket marketplaces (including but not limited to
              Namecheap, Afternic, Sedo, and Who.is) are provided for convenience only. NamingStorm does not
              control, endorse, or take responsibility for these third parties' content, pricing, availability
              claims, or transactions, and is not a party to any transaction you enter into with them.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">6. Assumption of Risk; Use at Your Own Risk</h2>
            <p>
              By using NamingStorm, you acknowledge that naming, branding, domain registration, and
              trademark filing carry inherent legal and financial risk, and you agree that you use this
              service, and act on anything it generates or displays, entirely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">7. Service Provided "As Is"</h2>
            <p>
              The service is provided "as is" and "as available," without warranties of any kind, express
              or implied, including without limitation warranties of merchantability, fitness for a
              particular purpose, non-infringement, accuracy, or availability. We do not warrant that the
              service will be uninterrupted, error-free, or that any name it suggests is or will remain
              available or registrable.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, NamingStorm and its operators will not be liable for
              any indirect, incidental, special, consequential, or punitive damages, or any loss of profits,
              revenue, data, or goodwill, arising from or related to your use of the service — including
              losses arising from reliance on any AI-generated name, trademark screening result, or domain
              availability result — even if advised of the possibility of such damages. Where liability
              cannot be excluded under applicable law, our total liability is limited to the amount, if any,
              you paid us in the 12 months before the claim arose.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless NamingStorm and its operators from any claims,
              damages, losses, or expenses (including reasonable attorneys' fees) arising from your use of a
              name generated by this service, your registration or use of a domain, or your violation of
              these terms or any third party's rights.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">10. Changes to These Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the service after changes are
              posted constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-neutral-900 mb-3">11. Contact</h2>
            <p>
              Questions about these terms can be sent through the feedback tool inside the app.
            </p>
          </section>
        </div>

        <p className="text-xs text-neutral-400 mt-16 pt-8 border-t border-neutral-200">
          This page is a general-purpose starting draft based on common industry practice for AI naming and
          trademark-screening tools. It has not been reviewed by a licensed attorney and should not be
          treated as a complete or jurisdiction-specific legal document.
        </p>
      </div>
    </div>
  );
}
